services:
  package_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: kagemeka/$PROJECT:latest
    restart: on-failure
    runtime: nvidia
    tty: true
    volumes:
      - read_only: false
        source: $ROOT
        target: /root/$PROJECT
        type: bind
        volume:
          nocopy: true
    working_dir: /root/$PROJECT
version: '3.9'
